import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    id("org.jetbrains.kotlin.plugin.compose") version "2.2.10"
}

// Applied conditionally: both plugins hard-fail the build if google-services.json is
// missing, and that file can only be generated by registering the app in a Firebase
// project (console.firebase.google.com). Until that's done, the Firebase dependencies
// below still compile fine; only push/crash-reporting themselves stay inert.
val googleServicesJsonFile = file("google-services.json")
if (googleServicesJsonFile.exists()) {
    apply(plugin = "com.google.gms.google-services")
    apply(plugin = "com.google.firebase.crashlytics")
}

val keystorePropertiesFile = rootProject.file("keystore/keystore.properties")
val keystoreProperties = Properties().apply {
    if (keystorePropertiesFile.exists()) {
        load(keystorePropertiesFile.inputStream())
    }
}

android {
    namespace = "com.example.myapplication"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.finds.app"
        minSdk = 24
        targetSdk = 36
        versionCode = (project.property("VERSION_CODE") as String).toInt()
        versionName = project.property("VERSION_NAME") as String

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        create("release") {
            if (keystorePropertiesFile.exists()) {
                storeFile = rootProject.file("keystore/${keystoreProperties["storeFile"]}")
                storePassword = keystoreProperties["storePassword"] as String
                keyAlias = keystoreProperties["keyAlias"] as String
                keyPassword = keystoreProperties["keyPassword"] as String
            }
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }

    buildFeatures {
        viewBinding = true
        compose = true
        buildConfig = true
    }
}

dependencies {
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.activity)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.recyclerview)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.livedata.ktx)
    implementation("androidx.gridlayout:gridlayout:1.0.0")
    implementation(libs.glide)

    // Chat feature dependencies
    implementation("androidx.swiperefreshlayout:swiperefreshlayout:1.1.0")
    implementation("com.squareup.retrofit2:retrofit:2.9.0")
    implementation("com.squareup.retrofit2:converter-gson:2.9.0")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("com.squareup.okhttp3:logging-interceptor:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    implementation("com.facebook.shimmer:shimmer:0.5.0")

    // Push notifications (FCM) + crash reporting — share one Firebase project/BoM
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.messaging)
    implementation(libs.firebase.crashlytics)
    implementation(libs.kotlinx.coroutines.play.services)

    // Jetpack Compose dependencies
    val composeBom = platform("androidx.compose:compose-bom:2024.12.01")
    implementation(composeBom)
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.compose.material3:material3")

    // SVG loading (Coil + Coil SVG)
    implementation("io.coil-kt:coil:2.6.0")
    implementation("io.coil-kt:coil-svg:2.6.0")

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
}

// Copy logo images: "logo find light.png" -> drawable/ic_app_logo_full.png
//                   "logo find dark.png"  -> drawable-night/ic_app_logo_full.png
val logoLightFile = rootProject.file("ios code/logo find light.png")
val logoDarkFile = rootProject.file("ios code/logo find dark.png")
val androidLogoLight = project.file("src/main/res/drawable/ic_app_logo_full.png")
val androidLogoDark = project.file("src/main/res/drawable-night/ic_app_logo_full.png")

if (logoLightFile.exists()) {
    try {
        logoLightFile.copyTo(androidLogoLight, overwrite = true)
    } catch (_: Exception) {}
}
if (logoDarkFile.exists()) {
    try {
        androidLogoDark.parentFile.mkdirs()
        logoDarkFile.copyTo(androidLogoDark, overwrite = true)
    } catch (_: Exception) {}
}

tasks.register("copyAppLogos") {
    doLast {
        if (logoLightFile.exists()) {
            logoLightFile.copyTo(androidLogoLight, overwrite = true)
        }
        if (logoDarkFile.exists()) {
            androidLogoDark.parentFile.mkdirs()
            logoDarkFile.copyTo(androidLogoDark, overwrite = true)
        }
    }
}

val newIconResDir = rootProject.file("ios code/new icon/android/res")
if (newIconResDir.exists()) {
    try {
        newIconResDir.copyRecursively(project.file("src/main/res"), overwrite = true)
    } catch (_: Exception) {}
}

val playStoreFile = rootProject.file("ios code/new icon/android/play_store_512.png")
if (playStoreFile.exists()) {
    try {
        playStoreFile.copyTo(project.file("play_store_512.png"), overwrite = true)
    } catch (_: Exception) {}
}

tasks.register<Copy>("copyNewAppIcons") {
    from(rootProject.file("ios code/new icon/android/res"))
    into(project.file("src/main/res"))
    doLast {
        val playStoreSrc = rootProject.file("ios code/new icon/android/play_store_512.png")
        if (playStoreSrc.exists()) {
            playStoreSrc.copyTo(project.file("play_store_512.png"), overwrite = true)
        }
    }
}

tasks.matching { it.name == "preBuild" }.configureEach {
    dependsOn("copyAppLogos")
    dependsOn("copyNewAppIcons")
}
